# Generated by Django 4.0.3 on 2022-03-26 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_review_is_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['name']},
        ),
    ]
