# Generated by Django 4.0.3 on 2022-03-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birth_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('Professional', 'Professional'), ('Student', 'Student'), ('Hobbyist', 'Hobbyist')], max_length=12, null=True),
        ),
    ]
