# Generated by Django 4.0.2 on 2022-02-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
