# Generated by Django 4.0.2 on 2022-02-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='on_site',
            field=models.BooleanField(default=False),
        ),
    ]
