# Generated by Django 4.0.1 on 2022-01-30 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='store_categ_name_1278fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='store_produ_name_5e57da_idx',
        ),
    ]
