# Generated by Django 4.0.2 on 2022-02-22 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name_plural': 'Wish list'},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'verbose_name': 'Wish list item'},
        ),
    ]
