# Generated by Django 4.0.2 on 2022-03-06 18:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=250, primary_key=True, serialize=False),
        ),
    ]
